apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - azkaoru
    environmentGitOwner: azkaoru
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: azkaoru
    repository: jx3-beta-k8s
  - key: staging
  - key: production
  ingress:
    domain: cloudapps.dev.example.com
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: azkaoru
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
