jx:
  imagePullSecrets:
  - tekton-container-registry-auth
  secrets:
    adminUser:
      password: todo
      username: todo
    hmacToken: todo
    pipelineUser:
      email: jenkins-x@googlegroups.com
      token: todo
      username: jenkins-x-labs-bot
jxRequirements:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - azkaoru
    environmentGitOwner: azkaoru
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: azkaoru
    repository: jx3-beta-k8s
  - key: staging
  - key: production
  ingress:
    domain: cloudapps.dev.example.com
    externalDNS: false
    namespaceSubDomain: -nginx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: azkaoru
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
jxRequirementsIngressExternalDNS:
  enabled: false
jxRequirementsIngressTLS:
  enabled: false
jxRequirementsVault:
  enabled: false
