apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: jx-boot
    jenkins-x.io/kind: jx-git-operator
spec:
  backoffLimit: 4
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: jx-boot
        jenkins-x.io/kind: jx-git-operator
    spec:
      initContainers:
      - args:
        - gitops
        - git
        - clone
        command:
        - jx
        env:
        - name: XDG_CONFIG_HOME
          value: /workspace/xdg_config
        - name: https_proxy
          value: 172.19.0.3:8080
        - name: http_proxy
          value: 172.19.0.3:8080
        - name: no_proxy
          value: ".dev.example.com,10.96.0.1"
        image: gcr.io/jenkinsxio/jx-boot:3.1.18
        name: git-clone
        volumeMounts:
        - mountPath: /workspace
          name: workspace-volume
        workingDir: /workspace
      containers:
      - args:
        - apply
        command:
        - make
        env:
        - name: XDG_CONFIG_HOME
          value: /workspace/xdg_config
        - name: https_proxy
          value: 172.19.0.3:8080
        - name: http_proxy
          value: 172.19.0.3:8080
        - name: no_proxy
          value: ".dev.example.com,10.96.0.1"
        image: gcr.io/jenkinsxio/jx-boot:3.1.18
        imagePullPolicy: Always
        name: job
        volumeMounts:
        - mountPath: /workspace
          name: workspace-volume
        workingDir: /workspace/source
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      serviceAccountName: jx-boot-job
      terminationGracePeriodSeconds: 30
      volumes:
      - name: workspace-volume
        emptyDir: {}
